/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */


module.exports = {
  myAutogeneratedSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // '.' 即当前的文档文件夹
    },
  ],
  // mySidebar: [
  //   {
  //     type: 'html',
  //     defaultStyle: true, // 使用默认的菜单项目样式
  //     value: `
  //       <div style="display: flex;align-items: center;">
  //         <img src="/logo.jpg" alt="Sponsor" style="width: 44px;height: 44px;"/>
  //       </div>
  //     `
  //   },
  //   {
  //     type: 'doc',
  //     id: 'intro',
  //     label: 'Getting started',
  //   },
  //   'tags-docs',
  //   { // 外部链接
  //     type: 'link',
  //     label: 'Facebook', // 链接标签
  //     href: 'https://facebook.com', // 外部 URL
  //   },
  //   { // 内部链接
  //     type: 'link',
  //     label: '文档首页', // 链接标签
  //     href: '/', // 内部路径
  //   }
  // ]
  // docs: [
  //   {
  //     type: 'category',
  //     label: 'Guides',
  //     collapsible: true,
  //     collapsed: false,
  //     items: [
  //       'intro',
  //       {
  //         type: 'category',
  //         label: 'Docs',
  //         items: ['tags-docs'],
  //       },
  //     ],
  //   },
  // ],
}
