// 侧边栏

import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

// 默认情况下，Docusaurus 从 docs 文件夹结构生成侧边栏
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'autogenerated', // 自动生成
      dirName: '.'
    }
  ]
  // 手动创建侧边栏
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
}

export default sidebars
