name: yogeexu-docs-deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    name: yogeexu-docs-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Insatall Packages
        run: npm run install
      - name: Build Docsusaurus Docs
        run: npm run build

      - name: Deploy to Github Pages
        uses: peaceires/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
