name: Test Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Test Deploy Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Install dependencies
        run: npm install
      - name: Build website
        run: npm run build
